// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ui/input.proto

package ui

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// API规范和UI协议
// 名字
type Name struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string            `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Description          string            `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DocLink              string            `protobuf:"bytes,4,opt,name=docLink,proto3" json:"docLink,omitempty"`
	SubNames             []*Name           `protobuf:"bytes,5,rep,name=subNames,proto3" json:"subNames,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Name) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Name) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Name) GetDocLink() string {
	if m != nil {
		return m.DocLink
	}
	return ""
}

func (m *Name) GetSubNames() []*Name {
	if m != nil {
		return m.SubNames
	}
	return nil
}

func (m *Name) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输出域
type Output struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                *Name               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Fold                 *wrappers.BoolValue `protobuf:"bytes,3,opt,name=fold,proto3" json:"fold,omitempty"`
	Fields               []*OutputField      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	SubOutputs           []*Output           `protobuf:"bytes,5,rep,name=subOutputs,proto3" json:"subOutputs,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Output) GetTitle() *Name {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Output) GetFold() *wrappers.BoolValue {
	if m != nil {
		return m.Fold
	}
	return nil
}

func (m *Output) GetFields() []*OutputField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Output) GetSubOutputs() []*Output {
	if m != nil {
		return m.SubOutputs
	}
	return nil
}

func (m *Output) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输出项
type OutputField struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                *Name             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Value                []string          `protobuf:"bytes,3,rep,name=value,proto3" json:"value,omitempty"`
	Format               string            `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Mate                 map[string]string `protobuf:"bytes,50,rep,name=mate,proto3" json:"mate,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OutputField) Reset()         { *m = OutputField{} }
func (m *OutputField) String() string { return proto.CompactTextString(m) }
func (*OutputField) ProtoMessage()    {}
func (*OutputField) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{2}
}

func (m *OutputField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputField.Unmarshal(m, b)
}
func (m *OutputField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputField.Marshal(b, m, deterministic)
}
func (m *OutputField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputField.Merge(m, src)
}
func (m *OutputField) XXX_Size() int {
	return xxx_messageInfo_OutputField.Size(m)
}
func (m *OutputField) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputField.DiscardUnknown(m)
}

var xxx_messageInfo_OutputField proto.InternalMessageInfo

func (m *OutputField) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OutputField) GetTitle() *Name {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *OutputField) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *OutputField) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *OutputField) GetMate() map[string]string {
	if m != nil {
		return m.Mate
	}
	return nil
}

// 输入域
type Input struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                *Name               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Fold                 *wrappers.BoolValue `protobuf:"bytes,3,opt,name=fold,proto3" json:"fold,omitempty"`
	ShowType             string              `protobuf:"bytes,4,opt,name=showType,proto3" json:"showType,omitempty"`
	Fields               []*InputField       `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	SubInputs            []*Input            `protobuf:"bytes,6,rep,name=subInputs,proto3" json:"subInputs,omitempty"`
	Buttons              []*UrlAction        `protobuf:"bytes,7,rep,name=Buttons,proto3" json:"Buttons,omitempty"`
	UIFormVersion        string              `protobuf:"bytes,8,opt,name=UIFormVersion,proto3" json:"UIFormVersion,omitempty"`
	Tag                  map[string]string   `protobuf:"bytes,9,rep,name=tag,proto3" json:"tag,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{3}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Input) GetTitle() *Name {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Input) GetFold() *wrappers.BoolValue {
	if m != nil {
		return m.Fold
	}
	return nil
}

func (m *Input) GetShowType() string {
	if m != nil {
		return m.ShowType
	}
	return ""
}

func (m *Input) GetFields() []*InputField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Input) GetSubInputs() []*Input {
	if m != nil {
		return m.SubInputs
	}
	return nil
}

func (m *Input) GetButtons() []*UrlAction {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *Input) GetUIFormVersion() string {
	if m != nil {
		return m.UIFormVersion
	}
	return ""
}

func (m *Input) GetTag() map[string]string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *Input) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输入项
type InputField struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                *Name               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Edit                 *wrappers.BoolValue `protobuf:"bytes,3,opt,name=edit,proto3" json:"edit,omitempty"`
	Value                []string            `protobuf:"bytes,4,rep,name=value,proto3" json:"value,omitempty"`
	DefaultValue         []string            `protobuf:"bytes,5,rep,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	InputReacts          []*InputReact       `protobuf:"bytes,6,rep,name=inputReacts,proto3" json:"inputReacts,omitempty"`
	InputType            string              `protobuf:"bytes,7,opt,name=inputType,proto3" json:"inputType,omitempty"`
	Validate             *any.Any            `protobuf:"bytes,8,opt,name=validate,proto3" json:"validate,omitempty"`
	Buttons              []*InputField       `protobuf:"bytes,9,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Links                []*Name             `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Key                  string              `protobuf:"bytes,11,opt,name=key,proto3" json:"key,omitempty"`
	Tag                  map[string]string   `protobuf:"bytes,12,rep,name=tag,proto3" json:"tag,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Invisible            bool                `protobuf:"varint,13,opt,name=invisible,proto3" json:"invisible,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *InputField) Reset()         { *m = InputField{} }
func (m *InputField) String() string { return proto.CompactTextString(m) }
func (*InputField) ProtoMessage()    {}
func (*InputField) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{4}
}

func (m *InputField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputField.Unmarshal(m, b)
}
func (m *InputField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputField.Marshal(b, m, deterministic)
}
func (m *InputField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputField.Merge(m, src)
}
func (m *InputField) XXX_Size() int {
	return xxx_messageInfo_InputField.Size(m)
}
func (m *InputField) XXX_DiscardUnknown() {
	xxx_messageInfo_InputField.DiscardUnknown(m)
}

var xxx_messageInfo_InputField proto.InternalMessageInfo

func (m *InputField) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InputField) GetTitle() *Name {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *InputField) GetEdit() *wrappers.BoolValue {
	if m != nil {
		return m.Edit
	}
	return nil
}

func (m *InputField) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *InputField) GetDefaultValue() []string {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *InputField) GetInputReacts() []*InputReact {
	if m != nil {
		return m.InputReacts
	}
	return nil
}

func (m *InputField) GetInputType() string {
	if m != nil {
		return m.InputType
	}
	return ""
}

func (m *InputField) GetValidate() *any.Any {
	if m != nil {
		return m.Validate
	}
	return nil
}

func (m *InputField) GetButtons() []*InputField {
	if m != nil {
		return m.Buttons
	}
	return nil
}

func (m *InputField) GetLinks() []*Name {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *InputField) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InputField) GetTag() map[string]string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *InputField) GetInvisible() bool {
	if m != nil {
		return m.Invisible
	}
	return false
}

func (m *InputField) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输入文本
type ValidateInput struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Regex                string              `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
	RegexDes             string              `protobuf:"bytes,5,opt,name=regexDes,proto3" json:"regexDes,omitempty"`
	PlaceHolder          string              `protobuf:"bytes,6,opt,name=placeHolder,proto3" json:"placeHolder,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateInput) Reset()         { *m = ValidateInput{} }
func (m *ValidateInput) String() string { return proto.CompactTextString(m) }
func (*ValidateInput) ProtoMessage()    {}
func (*ValidateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{5}
}

func (m *ValidateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateInput.Unmarshal(m, b)
}
func (m *ValidateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateInput.Marshal(b, m, deterministic)
}
func (m *ValidateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateInput.Merge(m, src)
}
func (m *ValidateInput) XXX_Size() int {
	return xxx_messageInfo_ValidateInput.Size(m)
}
func (m *ValidateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateInput.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateInput proto.InternalMessageInfo

func (m *ValidateInput) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateInput) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateInput) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateInput) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *ValidateInput) GetRegexDes() string {
	if m != nil {
		return m.RegexDes
	}
	return ""
}

func (m *ValidateInput) GetPlaceHolder() string {
	if m != nil {
		return m.PlaceHolder
	}
	return ""
}

func (m *ValidateInput) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输入多条文本
type ValidateInputs struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Regex                string              `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
	RegexDes             string              `protobuf:"bytes,5,opt,name=regexDes,proto3" json:"regexDes,omitempty"`
	PlaceHolder          string              `protobuf:"bytes,6,opt,name=placeHolder,proto3" json:"placeHolder,omitempty"`
	MaxCount             int64               `protobuf:"varint,7,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	MinCount             int64               `protobuf:"varint,8,opt,name=minCount,proto3" json:"minCount,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateInputs) Reset()         { *m = ValidateInputs{} }
func (m *ValidateInputs) String() string { return proto.CompactTextString(m) }
func (*ValidateInputs) ProtoMessage()    {}
func (*ValidateInputs) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{6}
}

func (m *ValidateInputs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateInputs.Unmarshal(m, b)
}
func (m *ValidateInputs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateInputs.Marshal(b, m, deterministic)
}
func (m *ValidateInputs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateInputs.Merge(m, src)
}
func (m *ValidateInputs) XXX_Size() int {
	return xxx_messageInfo_ValidateInputs.Size(m)
}
func (m *ValidateInputs) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateInputs.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateInputs proto.InternalMessageInfo

func (m *ValidateInputs) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateInputs) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateInputs) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateInputs) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *ValidateInputs) GetRegexDes() string {
	if m != nil {
		return m.RegexDes
	}
	return ""
}

func (m *ValidateInputs) GetPlaceHolder() string {
	if m != nil {
		return m.PlaceHolder
	}
	return ""
}

func (m *ValidateInputs) GetMaxCount() int64 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *ValidateInputs) GetMinCount() int64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *ValidateInputs) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输入数字
type ValidateNumber struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Step                 string              `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	Max                  string              `protobuf:"bytes,5,opt,name=max,proto3" json:"max,omitempty"`
	Min                  string              `protobuf:"bytes,6,opt,name=min,proto3" json:"min,omitempty"`
	Mid                  string              `protobuf:"bytes,7,opt,name=mid,proto3" json:"mid,omitempty"`
	Unit                 string              `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateNumber) Reset()         { *m = ValidateNumber{} }
func (m *ValidateNumber) String() string { return proto.CompactTextString(m) }
func (*ValidateNumber) ProtoMessage()    {}
func (*ValidateNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{7}
}

func (m *ValidateNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateNumber.Unmarshal(m, b)
}
func (m *ValidateNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateNumber.Marshal(b, m, deterministic)
}
func (m *ValidateNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateNumber.Merge(m, src)
}
func (m *ValidateNumber) XXX_Size() int {
	return xxx_messageInfo_ValidateNumber.Size(m)
}
func (m *ValidateNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateNumber proto.InternalMessageInfo

func (m *ValidateNumber) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateNumber) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateNumber) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateNumber) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *ValidateNumber) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *ValidateNumber) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *ValidateNumber) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *ValidateNumber) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *ValidateNumber) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输入多条数字
type ValidateNumbers struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Step                 string              `protobuf:"bytes,4,opt,name=step,proto3" json:"step,omitempty"`
	Max                  string              `protobuf:"bytes,5,opt,name=max,proto3" json:"max,omitempty"`
	Min                  string              `protobuf:"bytes,6,opt,name=min,proto3" json:"min,omitempty"`
	Mid                  string              `protobuf:"bytes,7,opt,name=mid,proto3" json:"mid,omitempty"`
	Unit                 string              `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	MaxCount             int64               `protobuf:"varint,9,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	MinCount             int64               `protobuf:"varint,10,opt,name=minCount,proto3" json:"minCount,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateNumbers) Reset()         { *m = ValidateNumbers{} }
func (m *ValidateNumbers) String() string { return proto.CompactTextString(m) }
func (*ValidateNumbers) ProtoMessage()    {}
func (*ValidateNumbers) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{8}
}

func (m *ValidateNumbers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateNumbers.Unmarshal(m, b)
}
func (m *ValidateNumbers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateNumbers.Marshal(b, m, deterministic)
}
func (m *ValidateNumbers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateNumbers.Merge(m, src)
}
func (m *ValidateNumbers) XXX_Size() int {
	return xxx_messageInfo_ValidateNumbers.Size(m)
}
func (m *ValidateNumbers) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateNumbers.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateNumbers proto.InternalMessageInfo

func (m *ValidateNumbers) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateNumbers) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateNumbers) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateNumbers) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *ValidateNumbers) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *ValidateNumbers) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *ValidateNumbers) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *ValidateNumbers) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *ValidateNumbers) GetMaxCount() int64 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *ValidateNumbers) GetMinCount() int64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *ValidateNumbers) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 开关
type ValidateSwitch struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateSwitch) Reset()         { *m = ValidateSwitch{} }
func (m *ValidateSwitch) String() string { return proto.CompactTextString(m) }
func (*ValidateSwitch) ProtoMessage()    {}
func (*ValidateSwitch) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{9}
}

func (m *ValidateSwitch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateSwitch.Unmarshal(m, b)
}
func (m *ValidateSwitch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateSwitch.Marshal(b, m, deterministic)
}
func (m *ValidateSwitch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateSwitch.Merge(m, src)
}
func (m *ValidateSwitch) XXX_Size() int {
	return xxx_messageInfo_ValidateSwitch.Size(m)
}
func (m *ValidateSwitch) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateSwitch.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateSwitch proto.InternalMessageInfo

func (m *ValidateSwitch) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateSwitch) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateSwitch) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateSwitch) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 选择器
type ValidateSelect struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Options              []*Name             `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	Labels               []string            `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	MaxCount             int64               `protobuf:"varint,5,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	MinCount             int64               `protobuf:"varint,6,opt,name=minCount,proto3" json:"minCount,omitempty"`
	PlaceHolder          string              `protobuf:"bytes,7,opt,name=placeHolder,proto3" json:"placeHolder,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateSelect) Reset()         { *m = ValidateSelect{} }
func (m *ValidateSelect) String() string { return proto.CompactTextString(m) }
func (*ValidateSelect) ProtoMessage()    {}
func (*ValidateSelect) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{10}
}

func (m *ValidateSelect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateSelect.Unmarshal(m, b)
}
func (m *ValidateSelect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateSelect.Marshal(b, m, deterministic)
}
func (m *ValidateSelect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateSelect.Merge(m, src)
}
func (m *ValidateSelect) XXX_Size() int {
	return xxx_messageInfo_ValidateSelect.Size(m)
}
func (m *ValidateSelect) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateSelect.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateSelect proto.InternalMessageInfo

func (m *ValidateSelect) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateSelect) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateSelect) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateSelect) GetOptions() []*Name {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ValidateSelect) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ValidateSelect) GetMaxCount() int64 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *ValidateSelect) GetMinCount() int64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *ValidateSelect) GetPlaceHolder() string {
	if m != nil {
		return m.PlaceHolder
	}
	return ""
}

func (m *ValidateSelect) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 上传文件
type ValidateFile struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Regex                string              `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
	RegexDes             string              `protobuf:"bytes,5,opt,name=regexDes,proto3" json:"regexDes,omitempty"`
	PlaceHolder          string              `protobuf:"bytes,6,opt,name=placeHolder,proto3" json:"placeHolder,omitempty"`
	FileName             []string            `protobuf:"bytes,7,rep,name=fileName,proto3" json:"fileName,omitempty"`
	FileNameRegex        string              `protobuf:"bytes,8,opt,name=fileNameRegex,proto3" json:"fileNameRegex,omitempty"`
	FileNameRegexDes     string              `protobuf:"bytes,9,opt,name=fileNameRegexDes,proto3" json:"fileNameRegexDes,omitempty"`
	FileNameSuffix       string              `protobuf:"bytes,10,opt,name=fileNameSuffix,proto3" json:"fileNameSuffix,omitempty"`
	Url                  string              `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	Min                  string              `protobuf:"bytes,12,opt,name=min,proto3" json:"min,omitempty"`
	Max                  string              `protobuf:"bytes,13,opt,name=max,proto3" json:"max,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateFile) Reset()         { *m = ValidateFile{} }
func (m *ValidateFile) String() string { return proto.CompactTextString(m) }
func (*ValidateFile) ProtoMessage()    {}
func (*ValidateFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{11}
}

func (m *ValidateFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateFile.Unmarshal(m, b)
}
func (m *ValidateFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateFile.Marshal(b, m, deterministic)
}
func (m *ValidateFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateFile.Merge(m, src)
}
func (m *ValidateFile) XXX_Size() int {
	return xxx_messageInfo_ValidateFile.Size(m)
}
func (m *ValidateFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateFile.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateFile proto.InternalMessageInfo

func (m *ValidateFile) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateFile) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateFile) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateFile) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *ValidateFile) GetRegexDes() string {
	if m != nil {
		return m.RegexDes
	}
	return ""
}

func (m *ValidateFile) GetPlaceHolder() string {
	if m != nil {
		return m.PlaceHolder
	}
	return ""
}

func (m *ValidateFile) GetFileName() []string {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *ValidateFile) GetFileNameRegex() string {
	if m != nil {
		return m.FileNameRegex
	}
	return ""
}

func (m *ValidateFile) GetFileNameRegexDes() string {
	if m != nil {
		return m.FileNameRegexDes
	}
	return ""
}

func (m *ValidateFile) GetFileNameSuffix() string {
	if m != nil {
		return m.FileNameSuffix
	}
	return ""
}

func (m *ValidateFile) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ValidateFile) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *ValidateFile) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *ValidateFile) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 上传多个文件
type ValidateFiles struct {
	ValidateDes          string              `protobuf:"bytes,1,opt,name=validateDes,proto3" json:"validateDes,omitempty"`
	Require              *wrappers.BoolValue `protobuf:"bytes,2,opt,name=require,proto3" json:"require,omitempty"`
	RequireDes           string              `protobuf:"bytes,3,opt,name=requireDes,proto3" json:"requireDes,omitempty"`
	Regex                string              `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
	RegexDes             string              `protobuf:"bytes,5,opt,name=regexDes,proto3" json:"regexDes,omitempty"`
	PlaceHolder          string              `protobuf:"bytes,6,opt,name=placeHolder,proto3" json:"placeHolder,omitempty"`
	FileName             []string            `protobuf:"bytes,7,rep,name=fileName,proto3" json:"fileName,omitempty"`
	FileNameRegex        string              `protobuf:"bytes,8,opt,name=fileNameRegex,proto3" json:"fileNameRegex,omitempty"`
	FileNameRegexDes     string              `protobuf:"bytes,9,opt,name=fileNameRegexDes,proto3" json:"fileNameRegexDes,omitempty"`
	MaxCount             int64               `protobuf:"varint,10,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	MinCount             int64               `protobuf:"varint,11,opt,name=minCount,proto3" json:"minCount,omitempty"`
	FileNameSuffix       string              `protobuf:"bytes,12,opt,name=fileNameSuffix,proto3" json:"fileNameSuffix,omitempty"`
	Url                  string              `protobuf:"bytes,13,opt,name=url,proto3" json:"url,omitempty"`
	Min                  string              `protobuf:"bytes,14,opt,name=min,proto3" json:"min,omitempty"`
	Max                  string              `protobuf:"bytes,15,opt,name=max,proto3" json:"max,omitempty"`
	Meta                 map[string]string   `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValidateFiles) Reset()         { *m = ValidateFiles{} }
func (m *ValidateFiles) String() string { return proto.CompactTextString(m) }
func (*ValidateFiles) ProtoMessage()    {}
func (*ValidateFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{12}
}

func (m *ValidateFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateFiles.Unmarshal(m, b)
}
func (m *ValidateFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateFiles.Marshal(b, m, deterministic)
}
func (m *ValidateFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateFiles.Merge(m, src)
}
func (m *ValidateFiles) XXX_Size() int {
	return xxx_messageInfo_ValidateFiles.Size(m)
}
func (m *ValidateFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateFiles.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateFiles proto.InternalMessageInfo

func (m *ValidateFiles) GetValidateDes() string {
	if m != nil {
		return m.ValidateDes
	}
	return ""
}

func (m *ValidateFiles) GetRequire() *wrappers.BoolValue {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *ValidateFiles) GetRequireDes() string {
	if m != nil {
		return m.RequireDes
	}
	return ""
}

func (m *ValidateFiles) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *ValidateFiles) GetRegexDes() string {
	if m != nil {
		return m.RegexDes
	}
	return ""
}

func (m *ValidateFiles) GetPlaceHolder() string {
	if m != nil {
		return m.PlaceHolder
	}
	return ""
}

func (m *ValidateFiles) GetFileName() []string {
	if m != nil {
		return m.FileName
	}
	return nil
}

func (m *ValidateFiles) GetFileNameRegex() string {
	if m != nil {
		return m.FileNameRegex
	}
	return ""
}

func (m *ValidateFiles) GetFileNameRegexDes() string {
	if m != nil {
		return m.FileNameRegexDes
	}
	return ""
}

func (m *ValidateFiles) GetMaxCount() int64 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *ValidateFiles) GetMinCount() int64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *ValidateFiles) GetFileNameSuffix() string {
	if m != nil {
		return m.FileNameSuffix
	}
	return ""
}

func (m *ValidateFiles) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ValidateFiles) GetMin() string {
	if m != nil {
		return m.Min
	}
	return ""
}

func (m *ValidateFiles) GetMax() string {
	if m != nil {
		return m.Max
	}
	return ""
}

func (m *ValidateFiles) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 输入联动
type InputReact struct {
	TriggerRegex         string            `protobuf:"bytes,1,opt,name=triggerRegex,proto3" json:"triggerRegex,omitempty"`
	ReactType            string            `protobuf:"bytes,2,opt,name=reactType,proto3" json:"reactType,omitempty"`
	UrlReact             *UrlAction        `protobuf:"bytes,3,opt,name=urlReact,proto3" json:"urlReact,omitempty"`
	Inputs               []*Input          `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	TargetInputId        string            `protobuf:"bytes,5,opt,name=targetInputId,proto3" json:"targetInputId,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InputReact) Reset()         { *m = InputReact{} }
func (m *InputReact) String() string { return proto.CompactTextString(m) }
func (*InputReact) ProtoMessage()    {}
func (*InputReact) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{13}
}

func (m *InputReact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputReact.Unmarshal(m, b)
}
func (m *InputReact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputReact.Marshal(b, m, deterministic)
}
func (m *InputReact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputReact.Merge(m, src)
}
func (m *InputReact) XXX_Size() int {
	return xxx_messageInfo_InputReact.Size(m)
}
func (m *InputReact) XXX_DiscardUnknown() {
	xxx_messageInfo_InputReact.DiscardUnknown(m)
}

var xxx_messageInfo_InputReact proto.InternalMessageInfo

func (m *InputReact) GetTriggerRegex() string {
	if m != nil {
		return m.TriggerRegex
	}
	return ""
}

func (m *InputReact) GetReactType() string {
	if m != nil {
		return m.ReactType
	}
	return ""
}

func (m *InputReact) GetUrlReact() *UrlAction {
	if m != nil {
		return m.UrlReact
	}
	return nil
}

func (m *InputReact) GetInputs() []*Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *InputReact) GetTargetInputId() string {
	if m != nil {
		return m.TargetInputId
	}
	return ""
}

func (m *InputReact) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 根据请求url显示输入项
type UrlAction struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *Name             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Method               string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string            `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Body                 *Input            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UrlAction) Reset()         { *m = UrlAction{} }
func (m *UrlAction) String() string { return proto.CompactTextString(m) }
func (*UrlAction) ProtoMessage()    {}
func (*UrlAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{14}
}

func (m *UrlAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UrlAction.Unmarshal(m, b)
}
func (m *UrlAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UrlAction.Marshal(b, m, deterministic)
}
func (m *UrlAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UrlAction.Merge(m, src)
}
func (m *UrlAction) XXX_Size() int {
	return xxx_messageInfo_UrlAction.Size(m)
}
func (m *UrlAction) XXX_DiscardUnknown() {
	xxx_messageInfo_UrlAction.DiscardUnknown(m)
}

var xxx_messageInfo_UrlAction proto.InternalMessageInfo

func (m *UrlAction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UrlAction) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UrlAction) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *UrlAction) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UrlAction) GetBody() *Input {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *UrlAction) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 资源列表
type Resources struct {
	ResourceBriefs       []*ResourceBrief  `protobuf:"bytes,1,rep,name=resourceBriefs,proto3" json:"resourceBriefs,omitempty"`
	Functions            []*UrlAction      `protobuf:"bytes,2,rep,name=functions,proto3" json:"functions,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{15}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetResourceBriefs() []*ResourceBrief {
	if m != nil {
		return m.ResourceBriefs
	}
	return nil
}

func (m *Resources) GetFunctions() []*UrlAction {
	if m != nil {
		return m.Functions
	}
	return nil
}

func (m *Resources) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 资源简介
type ResourceBrief struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               []*OutputField    `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Actions              []*UrlAction      `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResourceBrief) Reset()         { *m = ResourceBrief{} }
func (m *ResourceBrief) String() string { return proto.CompactTextString(m) }
func (*ResourceBrief) ProtoMessage()    {}
func (*ResourceBrief) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{16}
}

func (m *ResourceBrief) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceBrief.Unmarshal(m, b)
}
func (m *ResourceBrief) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceBrief.Marshal(b, m, deterministic)
}
func (m *ResourceBrief) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceBrief.Merge(m, src)
}
func (m *ResourceBrief) XXX_Size() int {
	return xxx_messageInfo_ResourceBrief.Size(m)
}
func (m *ResourceBrief) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceBrief.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceBrief proto.InternalMessageInfo

func (m *ResourceBrief) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResourceBrief) GetFields() []*OutputField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ResourceBrief) GetActions() []*UrlAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *ResourceBrief) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 资源
type Resource struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outputs              []*Output         `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Actions              []*UrlAction      `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,50,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{17}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Resource) GetActions() []*UrlAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Resource) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

// 菜单列表
type Menus struct {
	Menus                []*Menu  `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menus) Reset()         { *m = Menus{} }
func (m *Menus) String() string { return proto.CompactTextString(m) }
func (*Menus) ProtoMessage()    {}
func (*Menus) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{18}
}

func (m *Menus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menus.Unmarshal(m, b)
}
func (m *Menus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menus.Marshal(b, m, deterministic)
}
func (m *Menus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menus.Merge(m, src)
}
func (m *Menus) XXX_Size() int {
	return xxx_messageInfo_Menus.Size(m)
}
func (m *Menus) XXX_DiscardUnknown() {
	xxx_messageInfo_Menus.DiscardUnknown(m)
}

var xxx_messageInfo_Menus proto.InternalMessageInfo

func (m *Menus) GetMenus() []*Menu {
	if m != nil {
		return m.Menus
	}
	return nil
}

// 菜单项
type Menu struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	Name                 *Name    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Menu) Reset()         { *m = Menu{} }
func (m *Menu) String() string { return proto.CompactTextString(m) }
func (*Menu) ProtoMessage()    {}
func (*Menu) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{19}
}

func (m *Menu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Menu.Unmarshal(m, b)
}
func (m *Menu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Menu.Marshal(b, m, deterministic)
}
func (m *Menu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Menu.Merge(m, src)
}
func (m *Menu) XXX_Size() int {
	return xxx_messageInfo_Menu.Size(m)
}
func (m *Menu) XXX_DiscardUnknown() {
	xxx_messageInfo_Menu.DiscardUnknown(m)
}

var xxx_messageInfo_Menu proto.InternalMessageInfo

func (m *Menu) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *Menu) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

// 获取资源列表的请求参数
type GetResourcesReq struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	Filter               string   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Order                string   `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Sort                 string   `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Start                string   `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Size                 string   `protobuf:"bytes,6,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourcesReq) Reset()         { *m = GetResourcesReq{} }
func (m *GetResourcesReq) String() string { return proto.CompactTextString(m) }
func (*GetResourcesReq) ProtoMessage()    {}
func (*GetResourcesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{20}
}

func (m *GetResourcesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesReq.Unmarshal(m, b)
}
func (m *GetResourcesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesReq.Marshal(b, m, deterministic)
}
func (m *GetResourcesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesReq.Merge(m, src)
}
func (m *GetResourcesReq) XXX_Size() int {
	return xxx_messageInfo_GetResourcesReq.Size(m)
}
func (m *GetResourcesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesReq proto.InternalMessageInfo

func (m *GetResourcesReq) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *GetResourcesReq) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *GetResourcesReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *GetResourcesReq) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *GetResourcesReq) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetResourcesReq) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

// 查询资源详情
type GetResourceReq struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	ResourceId           string   `protobuf:"bytes,2,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourceReq) Reset()         { *m = GetResourceReq{} }
func (m *GetResourceReq) String() string { return proto.CompactTextString(m) }
func (*GetResourceReq) ProtoMessage()    {}
func (*GetResourceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{21}
}

func (m *GetResourceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceReq.Unmarshal(m, b)
}
func (m *GetResourceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceReq.Marshal(b, m, deterministic)
}
func (m *GetResourceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceReq.Merge(m, src)
}
func (m *GetResourceReq) XXX_Size() int {
	return xxx_messageInfo_GetResourceReq.Size(m)
}
func (m *GetResourceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceReq proto.InternalMessageInfo

func (m *GetResourceReq) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *GetResourceReq) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

// 获取执行资源动作的输入参数
type GetResourceActionInputReq struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	ResourceId           string   `protobuf:"bytes,2,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	ActionId             string   `protobuf:"bytes,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	ResourceType         string   `protobuf:"bytes,4,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	ResourceTypeID       string   `protobuf:"bytes,5,opt,name=resourceTypeID,proto3" json:"resourceTypeID,omitempty"`
	LifeCycleUUID        string   `protobuf:"bytes,6,opt,name=lifeCycleUUID,proto3" json:"lifeCycleUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourceActionInputReq) Reset()         { *m = GetResourceActionInputReq{} }
func (m *GetResourceActionInputReq) String() string { return proto.CompactTextString(m) }
func (*GetResourceActionInputReq) ProtoMessage()    {}
func (*GetResourceActionInputReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{22}
}

func (m *GetResourceActionInputReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceActionInputReq.Unmarshal(m, b)
}
func (m *GetResourceActionInputReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceActionInputReq.Marshal(b, m, deterministic)
}
func (m *GetResourceActionInputReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceActionInputReq.Merge(m, src)
}
func (m *GetResourceActionInputReq) XXX_Size() int {
	return xxx_messageInfo_GetResourceActionInputReq.Size(m)
}
func (m *GetResourceActionInputReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceActionInputReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceActionInputReq proto.InternalMessageInfo

func (m *GetResourceActionInputReq) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *GetResourceActionInputReq) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *GetResourceActionInputReq) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *GetResourceActionInputReq) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *GetResourceActionInputReq) GetResourceTypeID() string {
	if m != nil {
		return m.ResourceTypeID
	}
	return ""
}

func (m *GetResourceActionInputReq) GetLifeCycleUUID() string {
	if m != nil {
		return m.LifeCycleUUID
	}
	return ""
}

// 执行资源的某个动作
type DoResourceActionReq struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	ResourceId           string   `protobuf:"bytes,2,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	ActionId             string   `protobuf:"bytes,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	Input                *Input   `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	LifeCycleUUID        string   `protobuf:"bytes,5,opt,name=lifeCycleUUID,proto3" json:"lifeCycleUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoResourceActionReq) Reset()         { *m = DoResourceActionReq{} }
func (m *DoResourceActionReq) String() string { return proto.CompactTextString(m) }
func (*DoResourceActionReq) ProtoMessage()    {}
func (*DoResourceActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{23}
}

func (m *DoResourceActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoResourceActionReq.Unmarshal(m, b)
}
func (m *DoResourceActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoResourceActionReq.Marshal(b, m, deterministic)
}
func (m *DoResourceActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoResourceActionReq.Merge(m, src)
}
func (m *DoResourceActionReq) XXX_Size() int {
	return xxx_messageInfo_DoResourceActionReq.Size(m)
}
func (m *DoResourceActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DoResourceActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_DoResourceActionReq proto.InternalMessageInfo

func (m *DoResourceActionReq) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *DoResourceActionReq) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *DoResourceActionReq) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *DoResourceActionReq) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *DoResourceActionReq) GetLifeCycleUUID() string {
	if m != nil {
		return m.LifeCycleUUID
	}
	return ""
}

// 获取对资源集进行操作的输入参数
type GetResourcesFunctionReq struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	FunctionId           string   `protobuf:"bytes,2,opt,name=functionId,proto3" json:"functionId,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Order                string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Sort                 string   `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Start                string   `protobuf:"bytes,6,opt,name=start,proto3" json:"start,omitempty"`
	Size                 string   `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourcesFunctionReq) Reset()         { *m = GetResourcesFunctionReq{} }
func (m *GetResourcesFunctionReq) String() string { return proto.CompactTextString(m) }
func (*GetResourcesFunctionReq) ProtoMessage()    {}
func (*GetResourcesFunctionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{24}
}

func (m *GetResourcesFunctionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourcesFunctionReq.Unmarshal(m, b)
}
func (m *GetResourcesFunctionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourcesFunctionReq.Marshal(b, m, deterministic)
}
func (m *GetResourcesFunctionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourcesFunctionReq.Merge(m, src)
}
func (m *GetResourcesFunctionReq) XXX_Size() int {
	return xxx_messageInfo_GetResourcesFunctionReq.Size(m)
}
func (m *GetResourcesFunctionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourcesFunctionReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourcesFunctionReq proto.InternalMessageInfo

func (m *GetResourcesFunctionReq) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *GetResourcesFunctionReq) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *GetResourcesFunctionReq) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *GetResourcesFunctionReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *GetResourcesFunctionReq) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *GetResourcesFunctionReq) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetResourcesFunctionReq) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

// 对资源集进行操作
type DoResourcesFunctionReq struct {
	ResourcesId          string   `protobuf:"bytes,1,opt,name=resourcesId,proto3" json:"resourcesId,omitempty"`
	FunctionId           string   `protobuf:"bytes,2,opt,name=functionId,proto3" json:"functionId,omitempty"`
	Input                *Input   `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoResourcesFunctionReq) Reset()         { *m = DoResourcesFunctionReq{} }
func (m *DoResourcesFunctionReq) String() string { return proto.CompactTextString(m) }
func (*DoResourcesFunctionReq) ProtoMessage()    {}
func (*DoResourcesFunctionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{25}
}

func (m *DoResourcesFunctionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoResourcesFunctionReq.Unmarshal(m, b)
}
func (m *DoResourcesFunctionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoResourcesFunctionReq.Marshal(b, m, deterministic)
}
func (m *DoResourcesFunctionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoResourcesFunctionReq.Merge(m, src)
}
func (m *DoResourcesFunctionReq) XXX_Size() int {
	return xxx_messageInfo_DoResourcesFunctionReq.Size(m)
}
func (m *DoResourcesFunctionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DoResourcesFunctionReq.DiscardUnknown(m)
}

var xxx_messageInfo_DoResourcesFunctionReq proto.InternalMessageInfo

func (m *DoResourcesFunctionReq) GetResourcesId() string {
	if m != nil {
		return m.ResourcesId
	}
	return ""
}

func (m *DoResourcesFunctionReq) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *DoResourcesFunctionReq) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

// 驱动表数组
type DriverTables struct {
	Drivers              []*DriverTable `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DriverTables) Reset()         { *m = DriverTables{} }
func (m *DriverTables) String() string { return proto.CompactTextString(m) }
func (*DriverTables) ProtoMessage()    {}
func (*DriverTables) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{26}
}

func (m *DriverTables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverTables.Unmarshal(m, b)
}
func (m *DriverTables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverTables.Marshal(b, m, deterministic)
}
func (m *DriverTables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverTables.Merge(m, src)
}
func (m *DriverTables) XXX_Size() int {
	return xxx_messageInfo_DriverTables.Size(m)
}
func (m *DriverTables) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverTables.DiscardUnknown(m)
}

var xxx_messageInfo_DriverTables proto.InternalMessageInfo

func (m *DriverTables) GetDrivers() []*DriverTable {
	if m != nil {
		return m.Drivers
	}
	return nil
}

// 驱动表
type DriverTable struct {
	ID                   int64          `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TimeCreate           string         `protobuf:"bytes,2,opt,name=TimeCreate,proto3" json:"TimeCreate,omitempty"`
	TimeUpdate           string         `protobuf:"bytes,3,opt,name=TimeUpdate,proto3" json:"TimeUpdate,omitempty"`
	UUID                 string         `protobuf:"bytes,4,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name                 *Name          `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Version              string         `protobuf:"bytes,6,opt,name=Version,proto3" json:"Version,omitempty"`
	Logo                 string         `protobuf:"bytes,7,opt,name=Logo,proto3" json:"Logo,omitempty"`
	Type                 *Name          `protobuf:"bytes,8,opt,name=Type,proto3" json:"Type,omitempty"`
	Resources            []string       `protobuf:"bytes,9,rep,name=Resources,proto3" json:"Resources,omitempty"`
	Actions              []*ActionTable `protobuf:"bytes,10,rep,name=Actions,proto3" json:"Actions,omitempty"`
	Readme               string         `protobuf:"bytes,11,opt,name=Readme,proto3" json:"Readme,omitempty"`
	Tag                  string         `protobuf:"bytes,12,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DriverTable) Reset()         { *m = DriverTable{} }
func (m *DriverTable) String() string { return proto.CompactTextString(m) }
func (*DriverTable) ProtoMessage()    {}
func (*DriverTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{27}
}

func (m *DriverTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DriverTable.Unmarshal(m, b)
}
func (m *DriverTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DriverTable.Marshal(b, m, deterministic)
}
func (m *DriverTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DriverTable.Merge(m, src)
}
func (m *DriverTable) XXX_Size() int {
	return xxx_messageInfo_DriverTable.Size(m)
}
func (m *DriverTable) XXX_DiscardUnknown() {
	xxx_messageInfo_DriverTable.DiscardUnknown(m)
}

var xxx_messageInfo_DriverTable proto.InternalMessageInfo

func (m *DriverTable) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DriverTable) GetTimeCreate() string {
	if m != nil {
		return m.TimeCreate
	}
	return ""
}

func (m *DriverTable) GetTimeUpdate() string {
	if m != nil {
		return m.TimeUpdate
	}
	return ""
}

func (m *DriverTable) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *DriverTable) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *DriverTable) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DriverTable) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *DriverTable) GetType() *Name {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *DriverTable) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *DriverTable) GetActions() []*ActionTable {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *DriverTable) GetReadme() string {
	if m != nil {
		return m.Readme
	}
	return ""
}

func (m *DriverTable) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// 动作表
type ActionTable struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name                 *Name    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=Target,proto3" json:"Target,omitempty"`
	AvailableStates      []string `protobuf:"bytes,4,rep,name=AvailableStates,proto3" json:"AvailableStates,omitempty"`
	IsSystem             bool     `protobuf:"varint,5,opt,name=IsSystem,proto3" json:"IsSystem,omitempty"`
	Tag                  string   `protobuf:"bytes,6,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionTable) Reset()         { *m = ActionTable{} }
func (m *ActionTable) String() string { return proto.CompactTextString(m) }
func (*ActionTable) ProtoMessage()    {}
func (*ActionTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_42cd4c27d41a508f, []int{28}
}

func (m *ActionTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionTable.Unmarshal(m, b)
}
func (m *ActionTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionTable.Marshal(b, m, deterministic)
}
func (m *ActionTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionTable.Merge(m, src)
}
func (m *ActionTable) XXX_Size() int {
	return xxx_messageInfo_ActionTable.Size(m)
}
func (m *ActionTable) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionTable.DiscardUnknown(m)
}

var xxx_messageInfo_ActionTable proto.InternalMessageInfo

func (m *ActionTable) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *ActionTable) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ActionTable) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ActionTable) GetAvailableStates() []string {
	if m != nil {
		return m.AvailableStates
	}
	return nil
}

func (m *ActionTable) GetIsSystem() bool {
	if m != nil {
		return m.IsSystem
	}
	return false
}

func (m *ActionTable) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*Name)(nil), "ui.Name")
	proto.RegisterMapType((map[string]string)(nil), "ui.Name.MetaEntry")
	proto.RegisterType((*Output)(nil), "ui.Output")
	proto.RegisterMapType((map[string]string)(nil), "ui.Output.MetaEntry")
	proto.RegisterType((*OutputField)(nil), "ui.OutputField")
	proto.RegisterMapType((map[string]string)(nil), "ui.OutputField.MateEntry")
	proto.RegisterType((*Input)(nil), "ui.Input")
	proto.RegisterMapType((map[string]string)(nil), "ui.Input.MetaEntry")
	proto.RegisterMapType((map[string]string)(nil), "ui.Input.TagEntry")
	proto.RegisterType((*InputField)(nil), "ui.InputField")
	proto.RegisterMapType((map[string]string)(nil), "ui.InputField.MetaEntry")
	proto.RegisterMapType((map[string]string)(nil), "ui.InputField.TagEntry")
	proto.RegisterType((*ValidateInput)(nil), "ui.ValidateInput")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateInput.MetaEntry")
	proto.RegisterType((*ValidateInputs)(nil), "ui.ValidateInputs")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateInputs.MetaEntry")
	proto.RegisterType((*ValidateNumber)(nil), "ui.ValidateNumber")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateNumber.MetaEntry")
	proto.RegisterType((*ValidateNumbers)(nil), "ui.ValidateNumbers")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateNumbers.MetaEntry")
	proto.RegisterType((*ValidateSwitch)(nil), "ui.ValidateSwitch")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateSwitch.MetaEntry")
	proto.RegisterType((*ValidateSelect)(nil), "ui.ValidateSelect")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateSelect.MetaEntry")
	proto.RegisterType((*ValidateFile)(nil), "ui.ValidateFile")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateFile.MetaEntry")
	proto.RegisterType((*ValidateFiles)(nil), "ui.ValidateFiles")
	proto.RegisterMapType((map[string]string)(nil), "ui.ValidateFiles.MetaEntry")
	proto.RegisterType((*InputReact)(nil), "ui.InputReact")
	proto.RegisterMapType((map[string]string)(nil), "ui.InputReact.MetaEntry")
	proto.RegisterType((*UrlAction)(nil), "ui.UrlAction")
	proto.RegisterMapType((map[string]string)(nil), "ui.UrlAction.MetaEntry")
	proto.RegisterType((*Resources)(nil), "ui.Resources")
	proto.RegisterMapType((map[string]string)(nil), "ui.Resources.MetaEntry")
	proto.RegisterType((*ResourceBrief)(nil), "ui.ResourceBrief")
	proto.RegisterMapType((map[string]string)(nil), "ui.ResourceBrief.MetaEntry")
	proto.RegisterType((*Resource)(nil), "ui.Resource")
	proto.RegisterMapType((map[string]string)(nil), "ui.Resource.MetaEntry")
	proto.RegisterType((*Menus)(nil), "ui.Menus")
	proto.RegisterType((*Menu)(nil), "ui.Menu")
	proto.RegisterType((*GetResourcesReq)(nil), "ui.GetResourcesReq")
	proto.RegisterType((*GetResourceReq)(nil), "ui.GetResourceReq")
	proto.RegisterType((*GetResourceActionInputReq)(nil), "ui.GetResourceActionInputReq")
	proto.RegisterType((*DoResourceActionReq)(nil), "ui.DoResourceActionReq")
	proto.RegisterType((*GetResourcesFunctionReq)(nil), "ui.GetResourcesFunctionReq")
	proto.RegisterType((*DoResourcesFunctionReq)(nil), "ui.DoResourcesFunctionReq")
	proto.RegisterType((*DriverTables)(nil), "ui.DriverTables")
	proto.RegisterType((*DriverTable)(nil), "ui.DriverTable")
	proto.RegisterType((*ActionTable)(nil), "ui.ActionTable")
}

func init() { proto.RegisterFile("ui/input.proto", fileDescriptor_42cd4c27d41a508f) }

var fileDescriptor_42cd4c27d41a508f = []byte{
	// 1883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xcd, 0x8f, 0x1b, 0x49,
	0x15, 0x57, 0xdb, 0xed, 0x8f, 0x7e, 0x9e, 0xf1, 0x2c, 0xb5, 0xd1, 0xa4, 0x33, 0x64, 0xc3, 0x60,
	0x45, 0x99, 0x49, 0x16, 0x3c, 0x21, 0x20, 0x60, 0xb9, 0x25, 0x31, 0x03, 0x96, 0x36, 0x8b, 0xd4,
	0x99, 0xc9, 0x81, 0x5b, 0xdb, 0x5d, 0xf6, 0x94, 0xd2, 0xee, 0xf6, 0x56, 0x57, 0x4f, 0xc6, 0xf0,
	0x17, 0x20, 0x0e, 0xfc, 0x09, 0x70, 0xe5, 0xc4, 0x9d, 0x3b, 0x42, 0x5c, 0x22, 0x21, 0x4e, 0x88,
	0x23, 0x17, 0x24, 0xe0, 0xc4, 0x1f, 0x00, 0xaa, 0x57, 0x55, 0xfd, 0x65, 0x63, 0x4d, 0xa2, 0x86,
	0x48, 0xd1, 0xde, 0xea, 0xfd, 0x5e, 0xf9, 0xf5, 0xfb, 0xf8, 0xd5, 0xab, 0x0f, 0x43, 0x3f, 0x65,
	0x27, 0x2c, 0x5a, 0xa6, 0x62, 0xb8, 0xe4, 0xb1, 0x88, 0x49, 0x23, 0x65, 0x07, 0xb7, 0xe6, 0x71,
	0x3c, 0x0f, 0xe9, 0x09, 0x22, 0x93, 0x74, 0x76, 0xe2, 0x47, 0x2b, 0xa5, 0x3e, 0xb8, 0x53, 0x55,
	0xbd, 0xe2, 0xfe, 0x72, 0x49, 0x79, 0xa2, 0xf4, 0x83, 0x7f, 0x5a, 0x60, 0x7f, 0xe6, 0x2f, 0x28,
	0xe9, 0x43, 0x83, 0x05, 0xae, 0x75, 0x68, 0x1d, 0x3b, 0x5e, 0x83, 0x05, 0x84, 0x80, 0x2d, 0xe8,
	0x95, 0x70, 0x1b, 0x88, 0xe0, 0x98, 0x1c, 0x42, 0x2f, 0xa0, 0xc9, 0x94, 0xb3, 0xa5, 0x60, 0x71,
	0xe4, 0x36, 0x51, 0x55, 0x84, 0x88, 0x0b, 0x9d, 0x20, 0x9e, 0x7e, 0xca, 0xa2, 0x97, 0xae, 0x8d,
	0x5a, 0x23, 0x92, 0xbb, 0xd0, 0x4d, 0xd2, 0x89, 0xfc, 0x54, 0xe2, 0xb6, 0x0e, 0x9b, 0xc7, 0xbd,
	0x47, 0xdd, 0x61, 0xca, 0x86, 0x12, 0xf0, 0x32, 0x0d, 0xb9, 0x07, 0xf6, 0x82, 0x0a, 0xdf, 0x7d,
	0x84, 0x33, 0x88, 0x99, 0x31, 0x7c, 0x46, 0x85, 0xff, 0xfd, 0x48, 0xf0, 0x95, 0x87, 0xfa, 0x83,
	0xef, 0x80, 0x93, 0x41, 0xe4, 0x03, 0x68, 0xbe, 0xa4, 0x2b, 0xed, 0xbb, 0x1c, 0x92, 0x1b, 0xd0,
	0xba, 0xf4, 0xc3, 0x94, 0x6a, 0xef, 0x95, 0xf0, 0xbd, 0xc6, 0x77, 0xad, 0xc1, 0xaf, 0x1a, 0xd0,
	0xfe, 0x51, 0x2a, 0x96, 0xa9, 0x58, 0x8b, 0xf8, 0x0e, 0xb4, 0x04, 0x13, 0xa1, 0xfa, 0x51, 0xd1,
	0x3d, 0x05, 0x93, 0x21, 0xd8, 0xb3, 0x38, 0x0c, 0x30, 0xec, 0xde, 0xa3, 0x83, 0xa1, 0xca, 0xec,
	0xd0, 0x64, 0x76, 0xf8, 0x24, 0x8e, 0xc3, 0x17, 0xf2, 0x43, 0x1e, 0xce, 0x23, 0x47, 0xd0, 0x9e,
	0x31, 0x1a, 0x06, 0x89, 0x6b, 0x63, 0x34, 0x7b, 0xd2, 0xa0, 0xfa, 0xf6, 0xa9, 0xc4, 0x3d, 0xad,
	0x26, 0x0f, 0x00, 0x92, 0x74, 0xa2, 0x34, 0x26, 0x39, 0x90, 0x4f, 0xf6, 0x0a, 0x5a, 0x72, 0x5c,
	0x4a, 0xd0, 0x8d, 0x7c, 0x56, 0x7d, 0x29, 0xfa, 0x93, 0x05, 0xbd, 0x82, 0x9b, 0x6f, 0x9c, 0xa7,
	0xcc, 0x72, 0xf3, 0xb0, 0x99, 0x59, 0x26, 0xfb, 0xd0, 0x9e, 0xc5, 0x7c, 0xe1, 0x0b, 0x4d, 0x0c,
	0x2d, 0x91, 0xaf, 0x83, 0xbd, 0xf0, 0x05, 0xd5, 0x01, 0xdd, 0xaa, 0xe4, 0x68, 0xf8, 0xcc, 0x17,
	0xd4, 0x44, 0xe5, 0x0b, 0x8a, 0x51, 0x19, 0xe8, 0x8d, 0xa2, 0xfa, 0x6b, 0x13, 0x5a, 0xe3, 0xe8,
	0xff, 0x51, 0xf7, 0x03, 0xe8, 0x26, 0x17, 0xf1, 0xab, 0xb3, 0xd5, 0x92, 0xea, 0x58, 0x33, 0x99,
	0xdc, 0xcb, 0x38, 0xa1, 0xca, 0xdc, 0x97, 0x1f, 0x43, 0xb7, 0xca, 0x94, 0x38, 0x02, 0x27, 0x49,
	0x27, 0xa8, 0x48, 0xdc, 0x36, 0x4e, 0x75, 0xb2, 0xa9, 0x5e, 0xae, 0x23, 0x47, 0xd0, 0x79, 0x92,
	0x0a, 0x11, 0x47, 0x89, 0xdb, 0xc1, 0x69, 0xbb, 0x72, 0xda, 0x39, 0x0f, 0x1f, 0x4f, 0xe5, 0x82,
	0xf4, 0x8c, 0x96, 0xdc, 0x85, 0xdd, 0xf3, 0xf1, 0x69, 0xcc, 0x17, 0x2f, 0x28, 0x4f, 0xe4, 0xea,
	0xed, 0xa2, 0x6b, 0x65, 0x90, 0xdc, 0x85, 0xa6, 0xf0, 0xe7, 0xae, 0x93, 0x2f, 0x3f, 0xfc, 0xce,
	0xf0, 0xcc, 0x9f, 0xab, 0x2a, 0x48, 0x35, 0x39, 0x2a, 0x91, 0xf0, 0xc3, 0x7c, 0x5a, 0x95, 0x83,
	0xdf, 0x86, 0xae, 0xf9, 0xe5, 0x9b, 0x14, 0xeb, 0xed, 0xb9, 0xfb, 0x0f, 0x1b, 0x20, 0x4f, 0xe7,
	0xdb, 0x94, 0x9a, 0x06, 0x4c, 0x5c, 0xa7, 0xd4, 0x72, 0x5e, 0xee, 0x88, 0x5d, 0xa4, 0xfa, 0x00,
	0x76, 0x02, 0x3a, 0xf3, 0xd3, 0x50, 0xe0, 0x5c, 0x2c, 0xb5, 0xe3, 0x95, 0x30, 0xf2, 0x10, 0x7a,
	0xd8, 0xc5, 0x3d, 0xea, 0x4f, 0xb3, 0x12, 0xe7, 0x6c, 0x40, 0xd8, 0x2b, 0x4e, 0x21, 0xb7, 0xc1,
	0x41, 0x11, 0x79, 0xd5, 0xc1, 0x90, 0x72, 0x80, 0x3c, 0x84, 0xee, 0xa5, 0x1f, 0xb2, 0x40, 0x2e,
	0xa5, 0x2e, 0x7a, 0x7f, 0x63, 0xcd, 0xfb, 0xc7, 0xd1, 0xca, 0xcb, 0x66, 0x91, 0x63, 0xe8, 0x4c,
	0x34, 0x73, 0x9c, 0x8d, 0x5c, 0x34, 0x6a, 0x99, 0xb5, 0x90, 0x45, 0x2f, 0x13, 0x17, 0x2a, 0x7d,
	0x5b, 0xc1, 0xa6, 0x40, 0xbd, 0xbc, 0x40, 0xf7, 0x15, 0x8d, 0x76, 0x70, 0xfe, 0xcd, 0xb2, 0xdd,
	0x0a, 0x97, 0x30, 0xac, 0x4b, 0x96, 0xb0, 0x49, 0x48, 0xdd, 0xdd, 0x43, 0xeb, 0xb8, 0xeb, 0xe5,
	0x00, 0xf9, 0x5a, 0x89, 0x69, 0x6e, 0xc5, 0xd2, 0x3b, 0xa7, 0xdb, 0xef, 0x1a, 0xb0, 0xfb, 0x42,
	0x27, 0x54, 0x35, 0x97, 0x43, 0xe8, 0x99, 0x0c, 0x8f, 0x68, 0xa2, 0xad, 0x14, 0x21, 0xf2, 0x2d,
	0xe8, 0x70, 0xfa, 0x79, 0xca, 0xb8, 0x61, 0xe1, 0x36, 0x9a, 0x99, 0xa9, 0xe4, 0x0e, 0x80, 0x1e,
	0x4a, 0xb3, 0x6a, 0xe7, 0x2d, 0x20, 0xd2, 0x47, 0x4e, 0xe7, 0xf4, 0x4a, 0x77, 0x1c, 0x25, 0xc8,
	0x56, 0x84, 0x83, 0x11, 0x6e, 0xba, 0xd8, 0x8a, 0x8c, 0x2c, 0x3d, 0x5d, 0x86, 0xfe, 0x94, 0xfe,
	0x30, 0x0e, 0x03, 0xca, 0xdd, 0xb6, 0xf2, 0xb4, 0x00, 0x91, 0x93, 0x52, 0xf2, 0xbf, 0x2c, 0x93,
	0x5f, 0x0a, 0xb6, 0xbe, 0x2d, 0xe7, 0xdf, 0x0d, 0xe8, 0x97, 0x4c, 0x27, 0xef, 0x55, 0x22, 0x0f,
	0xa0, 0xbb, 0xf0, 0xaf, 0x9e, 0xc6, 0x69, 0x24, 0x70, 0xe5, 0x36, 0xbd, 0x4c, 0x46, 0x1d, 0x8b,
	0x94, 0xae, 0xab, 0x75, 0x5a, 0x26, 0x0f, 0x4b, 0x05, 0xb8, 0xbd, 0x56, 0x80, 0xa4, 0xbe, 0x0a,
	0xfc, 0xb1, 0x50, 0x81, 0xcf, 0xd2, 0xc5, 0x84, 0xf2, 0x77, 0x56, 0x01, 0x02, 0x76, 0x22, 0xe8,
	0x52, 0x17, 0x00, 0xc7, 0x32, 0x94, 0x85, 0x7f, 0xa5, 0x53, 0x2f, 0x87, 0x88, 0xb0, 0x48, 0x67,
	0x5b, 0x0e, 0x15, 0x12, 0xe8, 0xd6, 0x28, 0x87, 0xd2, 0x52, 0x1a, 0x31, 0xa1, 0xb7, 0x3a, 0x1c,
	0x6f, 0xcb, 0xa9, 0x8a, 0xbb, 0xbe, 0x9c, 0xfe, 0xbc, 0x09, 0x7b, 0x65, 0xdb, 0xc9, 0x7b, 0x9a,
	0xd4, 0x22, 0xc1, 0x9d, 0x2d, 0x04, 0x87, 0x0a, 0xc1, 0xbf, 0x51, 0x2a, 0xc6, 0x47, 0xeb, 0xc5,
	0xa8, 0x91, 0xe1, 0xff, 0xb2, 0x72, 0x86, 0x3f, 0x7f, 0xc5, 0xc4, 0xf4, 0xe2, 0x9d, 0x15, 0x63,
	0x0b, 0x07, 0x95, 0x67, 0xf5, 0x45, 0xfd, 0xb3, 0x66, 0x21, 0x6a, 0x1a, 0xd2, 0xe9, 0xbb, 0xdb,
	0xa2, 0x06, 0xd0, 0x89, 0xf1, 0x96, 0x68, 0x2e, 0x44, 0xf9, 0x41, 0xc2, 0x28, 0xe4, 0x2d, 0x21,
	0xf4, 0x27, 0x34, 0x4c, 0xdc, 0x2e, 0x1e, 0x9a, 0xb4, 0x54, 0x22, 0x58, 0x6b, 0x0b, 0xc1, 0xda,
	0x15, 0x82, 0x55, 0x7a, 0x73, 0x67, 0xbd, 0x37, 0x6f, 0xab, 0x05, 0xe6, 0xab, 0xbe, 0x5a, 0xfc,
	0xc2, 0x86, 0x1d, 0x63, 0xfb, 0x94, 0x85, 0xf4, 0x7d, 0xdb, 0xe3, 0x66, 0x2c, 0xa4, 0xb2, 0x9c,
	0x78, 0x13, 0x71, 0xbc, 0x4c, 0x96, 0x77, 0x0f, 0x33, 0xf6, 0xf0, 0xbb, 0xfa, 0xee, 0x51, 0x02,
	0xc9, 0x03, 0xf8, 0xa0, 0x04, 0x48, 0x3f, 0x1c, 0x9c, 0xb8, 0x86, 0x93, 0x7b, 0xd0, 0x37, 0xd8,
	0xf3, 0x74, 0x36, 0x63, 0x57, 0xd8, 0x5a, 0x1c, 0xaf, 0x82, 0xca, 0xf2, 0xa4, 0x3c, 0x34, 0x47,
	0xd3, 0x94, 0x87, 0xa6, 0xc5, 0xed, 0x94, 0x5b, 0x9c, 0x7f, 0x85, 0x67, 0x4f, 0xdd, 0x06, 0x87,
	0x25, 0x4e, 0x1c, 0x14, 0x39, 0x21, 0xeb, 0x56, 0x1f, 0x23, 0xfe, 0x60, 0xe7, 0xe7, 0x47, 0x69,
	0x39, 0xf9, 0x82, 0x12, 0x6f, 0x4d, 0x89, 0x62, 0x8b, 0x80, 0x2d, 0x2d, 0xa2, 0x57, 0x69, 0x11,
	0xeb, 0x54, 0xda, 0xd9, 0x46, 0xa5, 0xdd, 0x35, 0x2a, 0xf5, 0xd7, 0xa8, 0xb4, 0x97, 0x53, 0x69,
	0xcb, 0x19, 0x1a, 0x0b, 0x5e, 0x1f, 0x97, 0x7e, 0xdd, 0xd0, 0x57, 0x5f, 0xbc, 0x2f, 0xca, 0x4b,
	0xa8, 0xe0, 0x6c, 0x3e, 0xa7, 0x5c, 0xe5, 0x57, 0xd9, 0x28, 0x61, 0xf2, 0xee, 0xc5, 0xe5, 0x64,
	0xbc, 0x52, 0x2a, 0x83, 0x39, 0x40, 0xee, 0x43, 0x37, 0xe5, 0x21, 0x5a, 0xd3, 0x17, 0xe2, 0xca,
	0xdb, 0x42, 0xa6, 0x26, 0x5f, 0x85, 0x36, 0x53, 0x6f, 0x15, 0x76, 0xf5, 0xad, 0x42, 0x2b, 0x64,
	0xc1, 0x85, 0xcf, 0xe7, 0x54, 0x20, 0x3c, 0x0e, 0x34, 0x9f, 0xca, 0xe0, 0x7f, 0xbd, 0xef, 0xe1,
	0x67, 0xea, 0xcb, 0xd5, 0xdf, 0x2c, 0x70, 0xb2, 0x38, 0xd6, 0x5e, 0x09, 0x6e, 0x83, 0x1d, 0x49,
	0xce, 0x56, 0x1f, 0x09, 0x10, 0x95, 0x5b, 0xd4, 0x82, 0x8a, 0x8b, 0x38, 0xd0, 0xab, 0x48, 0x4b,
	0x86, 0x1f, 0x76, 0xce, 0x8f, 0x8f, 0xc0, 0x9e, 0xc4, 0xc1, 0x0a, 0x23, 0x2d, 0xe5, 0x04, 0x61,
	0xf2, 0x71, 0x29, 0xd6, 0x9b, 0xa5, 0xdc, 0xd6, 0x17, 0xea, 0x9f, 0x2d, 0x70, 0x3c, 0x9a, 0xc4,
	0x29, 0x9f, 0xd2, 0x84, 0x7c, 0x02, 0x7d, 0xae, 0x85, 0x27, 0x9c, 0xd1, 0x99, 0xec, 0x30, 0xf2,
	0xeb, 0x5f, 0x92, 0x5f, 0xf7, 0x8a, 0x1a, 0xaf, 0x32, 0x91, 0x7c, 0x0c, 0xce, 0x2c, 0x8d, 0xa6,
	0x6a, 0x03, 0x6f, 0x6c, 0x7a, 0x6b, 0xca, 0xf5, 0x9b, 0x62, 0xcb, 0x9c, 0xa8, 0x2f, 0xb6, 0xbf,
	0x58, 0xb0, 0x5b, 0x72, 0x7a, 0xad, 0x94, 0xf9, 0x1b, 0x6c, 0x63, 0xfb, 0x1b, 0xec, 0x11, 0x74,
	0x7c, 0x1d, 0x5b, 0x73, 0xe3, 0x3b, 0x9a, 0xd6, 0x6e, 0x5a, 0xd0, 0x25, 0x17, 0xea, 0x8b, 0xee,
	0xb5, 0x05, 0x5d, 0x63, 0x7a, 0x2d, 0xb0, 0xbb, 0xd0, 0x89, 0xf5, 0x83, 0x71, 0x63, 0xed, 0xc1,
	0xd8, 0xa8, 0xae, 0x1f, 0xd5, 0x83, 0x52, 0x54, 0xfb, 0xc5, 0xa8, 0xea, 0x0b, 0xe8, 0x08, 0x5a,
	0xcf, 0x68, 0x94, 0xe2, 0x83, 0xd2, 0x42, 0x0e, 0x34, 0xf9, 0x70, 0x85, 0x49, 0x8d, 0xa7, 0xe0,
	0xc1, 0x29, 0xd8, 0x52, 0x94, 0x5b, 0x8c, 0x21, 0x61, 0x32, 0x36, 0xd1, 0x17, 0xa1, 0xed, 0x4b,
	0x75, 0xf0, 0x4b, 0x0b, 0xf6, 0x7e, 0x40, 0x45, 0xc6, 0x3c, 0x8f, 0x7e, 0x7e, 0x0d, 0x9b, 0xfb,
	0x92, 0x33, 0xa1, 0xa0, 0x5c, 0x47, 0xa0, 0x25, 0x19, 0x58, 0xcc, 0xe5, 0x56, 0xa7, 0xd6, 0xbd,
	0x12, 0xf0, 0x62, 0x15, 0x73, 0x91, 0x5d, 0xac, 0x62, 0x8e, 0xcf, 0x82, 0x89, 0xf0, 0xb9, 0xd0,
	0x3d, 0x4e, 0x09, 0x38, 0x93, 0xfd, 0x84, 0xea, 0x9d, 0x12, 0xc7, 0x03, 0x0f, 0xfa, 0x05, 0x07,
	0xaf, 0xe7, 0x1f, 0x6e, 0xe5, 0x4a, 0x1c, 0x07, 0xda, 0xc7, 0x02, 0x32, 0xf8, 0xbb, 0x05, 0xb7,
	0x0a, 0x46, 0x55, 0xa9, 0x75, 0x17, 0xad, 0xc1, 0xbe, 0xdc, 0x4c, 0x15, 0x6d, 0xc6, 0xa6, 0x05,
	0x66, 0xb2, 0xdc, 0x75, 0xcc, 0xcc, 0xc2, 0xfb, 0x77, 0x09, 0x93, 0x1b, 0x6e, 0x51, 0x1e, 0x8f,
	0x74, 0x9a, 0x2a, 0xa8, 0xdc, 0x31, 0x42, 0x36, 0xa3, 0x4f, 0x57, 0xd3, 0x90, 0x9e, 0x9f, 0x8f,
	0x47, 0x3a, 0x71, 0x65, 0x70, 0xf0, 0x5b, 0x0b, 0x3e, 0x1c, 0xc5, 0xe5, 0x60, 0xff, 0xf7, 0x71,
	0x7e, 0x05, 0x5a, 0xb8, 0xaf, 0x61, 0x80, 0xa5, 0xde, 0xae, 0xf0, 0x75, 0xe7, 0x5b, 0x9b, 0x9c,
	0xff, 0xbd, 0x05, 0x37, 0x8b, 0x04, 0x3d, 0xd5, 0x0d, 0xf4, 0xda, 0x01, 0x98, 0x8e, 0x9b, 0x07,
	0x90, 0x23, 0x05, 0x22, 0x37, 0x37, 0x13, 0xd9, 0xde, 0x44, 0xe4, 0xd6, 0x26, 0x22, 0xb7, 0x37,
	0x11, 0xb9, 0x53, 0x20, 0xf2, 0x4f, 0x61, 0x3f, 0xaf, 0x42, 0xcd, 0x71, 0x64, 0xc9, 0x6e, 0x6e,
	0x4e, 0xf6, 0xe0, 0x13, 0xd8, 0x19, 0x71, 0x76, 0x49, 0xf9, 0x99, 0x3f, 0x91, 0x87, 0xe8, 0xfb,
	0xd0, 0x09, 0x50, 0x36, 0x1d, 0x06, 0xdb, 0x7e, 0x61, 0x8a, 0x67, 0xf4, 0x83, 0xd7, 0x0d, 0xe8,
	0x15, 0x14, 0xb2, 0xcf, 0x8e, 0x47, 0xe8, 0x64, 0xd3, 0x6b, 0x8c, 0x47, 0xd2, 0xb7, 0x33, 0xb6,
	0xa0, 0x4f, 0x39, 0xf5, 0x85, 0x69, 0x69, 0x05, 0xc4, 0xe8, 0xcf, 0x97, 0xf8, 0xf2, 0xde, 0xcc,
	0xf5, 0x0a, 0x91, 0xb9, 0xc2, 0xf2, 0xeb, 0xf6, 0x20, 0xc7, 0xb2, 0x69, 0xe1, 0x99, 0xb8, 0x55,
	0x6d, 0x5a, 0x78, 0x32, 0x76, 0xa1, 0x63, 0xfe, 0xa2, 0x51, 0x59, 0x37, 0xa2, 0xb4, 0xf5, 0x69,
	0x3c, 0x8f, 0x4d, 0xde, 0xe5, 0x58, 0xda, 0xc2, 0x85, 0xd6, 0xad, 0xda, 0xc2, 0xa5, 0x76, 0xbb,
	0xb0, 0xf7, 0xe3, 0x2b, 0xbf, 0xe3, 0x15, 0x0e, 0x03, 0xf7, 0xa1, 0xf3, 0x58, 0xef, 0x0e, 0x90,
	0xa7, 0x49, 0x41, 0x3a, 0x4d, 0x5a, 0x2f, 0xa9, 0xe4, 0x51, 0x3f, 0x58, 0x50, 0x7d, 0x95, 0xd2,
	0x92, 0x6c, 0xff, 0x67, 0xf8, 0xd0, 0x8f, 0xed, 0xff, 0xcc, 0x9f, 0x0f, 0x7e, 0x63, 0x41, 0xaf,
	0x60, 0x22, 0x4b, 0x80, 0xb5, 0x21, 0x01, 0x8d, 0x8d, 0x09, 0xd8, 0x87, 0xf6, 0x19, 0x1e, 0x0a,
	0x0d, 0x6d, 0x95, 0x44, 0x8e, 0x61, 0xef, 0xf1, 0xa5, 0xcf, 0x42, 0x69, 0xf6, 0xb9, 0xf0, 0x05,
	0x4d, 0xf4, 0xdf, 0x2e, 0x55, 0x58, 0xae, 0xdc, 0x71, 0xf2, 0x7c, 0x95, 0x08, 0xba, 0xc0, 0x24,
	0x77, 0xbd, 0x4c, 0x36, 0x1e, 0xb7, 0x33, 0x8f, 0x9f, 0x1c, 0xff, 0xf8, 0xde, 0x9c, 0x89, 0xe1,
	0xc5, 0x6a, 0x49, 0xf9, 0xf4, 0xc2, 0x67, 0xd1, 0x70, 0x1a, 0x9d, 0x4c, 0xc2, 0x78, 0x3a, 0xf3,
	0xa7, 0xfa, 0x8f, 0xf3, 0x69, 0x1c, 0x9e, 0xa4, 0x6c, 0xd2, 0x46, 0xe1, 0x9b, 0xff, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0x67, 0xcd, 0x70, 0x84, 0x1f, 0x00, 0x00,
}
